name: Update wiki posts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: Update wiki posts

    steps:
      # Clone posts repository
      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      # Clone wiki repository
      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/wiki-website"
          path: "wiki"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      # Install hunspell and English and Romanian dictionaries
      - name: Install hunspell and dictionaries
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-en-us hunspell-ro

      # Update posts
      - name: Update posts
        if: always()
        shell: bash
        run: |
          mkdir ./wiki/new_wiki
          mv -f ./wiki/wiki/.vitepress ./wiki/new_wiki
          mv -f ./posts/* ./wiki/new_wiki
          rm -rf ./wiki/wiki
          mv -f ./wiki/new_wiki ./wiki/wiki
          
          # Function to filter out correctly spelled English words
          filter_english() {
              while read -r line; do
                  # Check if the word is correctly spelled English word
                  if ! grep -q "^$line$" /usr/share/hunspell/en_US.dic; then
                      echo "$line"
                  fi
              done
          }

          # Function to filter out correctly spelled Romanian words
          filter_romanian() {
              while read -r line; do
                  # Check if the word is correctly spelled Romanian word
                  if ! grep -q "^$line$" /usr/share/hunspell/ro_RO.dic; then
                      echo "$line"
                  fi
              done
          }

          # Check for typos in English and store the result in a file
          hunspell -d en_US -l -i utf-8 ./wiki/wiki/* | filter_english > english_typos.txt || true

          # Check for typos in Romanian and store the result in a file
          hunspell -d ro_RO -l -i utf-8 ./wiki/wiki/* | filter_romanian > romanian_typos.txt || true

          # Combine the results
          cat english_typos.txt romanian_typos.txt > typos.txt

          # If typos are found, create an issue with the list of typos and fail the action
          if [ -s "typos.txt" ]; then
              echo "Typos found:"
              cat typos.txt
              # Format typos in Markdown
              echo -e "### Typos Found:\n\`\`\`\n$(cat typos.txt)\n\`\`\`" > formatted_typos.md
              # Create issue using GitHub REST API
              echo "Creating issue..."
              # Escape special characters in the issue body
              body=$(cat formatted_typos.md | jq -Rs 'gsub("\\\"";"\"")')
              # Create issue with escaped body
              curl -X POST -H "Authorization: token ${{ secrets.CI_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -d "{\"title\":\"Typos Found in Wiki\",\"body\":$body}" "https://api.github.com/repos/ragebhood/wiki/issues"
              # Fail the action
              exit 1
          fi
          
          cd wiki
          git config --global user.email "b-hood.ro@github.com"
          git config --global user.name "b-hood.ro"
          git status
          git add .
          git commit -m "Update posts with ${{ github.sha }}" || true
          git push || true
