name: Update wiki posts
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: "Update wiki posts" 
    steps:  
      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/wiki-website"
          path: "wiki"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      - name: Check spelling with Typos Action
        uses: crate-ci/typos@master
        with:
          files: ./wiki
          write_changes: false
