name: Update wiki posts
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: "Update posts" 
    steps:
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # Check all markdown and html files in repo (default)
          args: --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst'
          # Use json as output format (instead of markdown)
          format: json
          # Use different output file path
          output: /tmp/foo.txt
          # Use a custom GitHub token, which 
          token: ${{ secrets.CI_TOKEN }}
          # Fail action on broken links
          fail: true

      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/wiki-website"
          path: "wiki"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      - name: Update posts
        if: always()
        shell: bash
        run: |
          mkdir ./wiki/new_wiki
          mv -f ./wiki/wiki/.vitepress ./wiki/new_wiki
          mv -f ./posts/* ./wiki/new_wiki
          rm -rf ./wiki/wiki
          mv -f ./wiki/new_wiki ./wiki/wiki
          cd wiki
          git config --global user.email "b-hood.ro@github.com"
          git config --global user.name "b-hood.ro"
          git status
          git add .
          git commit -m "Update posts with ${{ github.sha }}" || true
          git push || true
