name: Update wiki posts

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-posts:
    runs-on: ubuntu-latest
    name: Update wiki posts

    steps:
      # Clone posts repository
      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      # Clone wiki repository
      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/wiki-website"
          path: "wiki"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      # Install hunspell and Romanian dictionary
      - name: Install hunspell and Romanian dictionary
        run: sudo apt-get install hunspell hunspell-ro

      # Update posts
      - name: Update posts
        if: always()
        shell: bash
        run: |
          mkdir ./wiki/new_wiki
          mv -f ./wiki/wiki/.vitepress ./wiki/new_wiki
          mv -f ./posts/* ./wiki/new_wiki
          rm -rf ./wiki/wiki
          mv -f ./wiki/new_wiki ./wiki/wiki
          hunspell -d ro_RO -l -i utf-8 ./wiki/wiki/* || true
          cd wiki
          git config --global user.email "b-hood.ro@github.com"
          git config --global user.name "b-hood.ro"
          git status
          git add .
          git commit -m "Update posts with ${{ github.sha }}" || true
          git push || true
