name: Update wiki posts
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  broken_link_checker_job:
      runs-on: ubuntu-latest
      name: Check for broken links
      steps:
        - name: Check for broken links
          id: link-report
          uses: celinekurpershoek/link-checker@v1.0.2
          with:
            # Required:
            url: "https://..."
            # optional:
            honorRobotExclusions: false
            ignorePatterns: "github,google"
            recursiveLinks: false # Check all URLs on all reachable pages (could take a while)
        - name: Get the result
          run: echo "${{steps.link-report.outputs.result}}"
  update-posts:
    runs-on: ubuntu-latest
    name: "Update posts" 
    steps:
      - name: Clone posts repository
        uses: actions/checkout@v3
        with:
          clean: true
          path: "posts"
          token: ${{ secrets.CI_TOKEN }}

      - name: Clone wiki repository
        uses: actions/checkout@v3
        with:
          clean: true
          repository: "cibucristi/wiki-website"
          path: "wiki"
          ref: "main"
          token: ${{ secrets.CI_TOKEN }}

      - name: Update posts
        if: always()
        shell: bash
        run: |
          mkdir ./wiki/new_wiki
          mv -f ./wiki/wiki/.vitepress ./wiki/new_wiki
          mv -f ./posts/* ./wiki/new_wiki
          rm -rf ./wiki/wiki
          mv -f ./wiki/new_wiki ./wiki/wiki
          cd wiki
          git config --global user.email "b-hood.ro@github.com"
          git config --global user.name "b-hood.ro"
          git status
          git add .
          git commit -m "Update posts with ${{ github.sha }}" || true
          git push || true
